---
title: "Dates and Times"
output: github_document
---

```{r}
library(tidyverse)
library(lubridate)
library(nycflights13)
library(dplyr)

```

Three types of date/time

Date. Tibbles print this as <date>
time .... print as <time>
date-time uniquely identifies and instant in time, typically to the nearest second.

Exercises 16.2.4
1. The string will cause it to return an NA value.
2. tzone deals with Time ZONEs hence tzone.It allows you to change the tz away from the system default.
3. 
```{r}
d1 <- "January 1, 2010"
mdy(d1)
d2 <- "2015-Mar-07"
ymd(d2)
d3 <- "06-Jun-2017"
dmy(d3)
d4 <- c("August 19 (2015)", "July 1 (2015)")
mdy(d4)
d5 <- "12/30/14" # Dec 30, 2014
mdy(d5)


```

```{r}
make_datetime_100 <- function(year, month, day, time) {
  make_datetime(year, month, day, time %/% 100, time %% 100)
}

flights_dt <- flights %>%
  filter(!is.na(dep_time), !is.na(arr_time)) %>%
  mutate(
    dep_time = make_datetime_100(year, month, day, dep_time),
    arr_time = make_datetime_100(year, month, day, arr_time),
    sched_dep_time_time = make_datetime_100(year, month, day, sched_dep_time),
    sched_arr_time = make_datetime_100(year, month, day, sched_arr_time),
  )%>%
  select(origin, dest, ends_with("delay"), ends_with("time"))
flights_dt

#flights_dt %>%
  #filter(!is.na(dep_time)) %>%
  
```

